
---
title: "Data_Vis_Group_Project"
author: "Carlota Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: true
    toc: yes
    toc_float: yes
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r libraries, include=FALSE}
#Load the corresponding libraries
library(tidyverse)
library(extrafont)
library(vroom)
library(ggtext)
library(gapminder)
library(ggrepel)
library(patchwork)
library(gghighlight)
library(skimr)
library(here)
library(plotly)
library(xlsx)

#remotes::install_github("kjhealy/nycdogs")
library(nycdogs)
library(sf) # for geospatial visualisation

#Windows
#loadfonts(device="win")
#MAC
loadfonts(device="pdf")
```

```{r read in the data}
#Read in the data
userBasedData_raw <- read.csv(file="Morocco.csv",header=TRUE,na.strings=c("..","NA"))

#Take a quick look at what is in the data
#glimpse(userBasedData_raw)

```


```{r}
Morocco_sample <- userBasedData_raw %>%
  select(Country.Name,Country.Code,Series,X2018..YR2018.)%>%
  filter(Series=="Total net enrolment rate, primary, both sexes (%)")

Morocco_sample2 <- userBasedData_raw %>%
  #filter(Country.Name=="Germany",Series=="Total net enrolment rate, primary, both sexes (%)")
  filter(Country.Name=="France",Series=="Gross enrolment ratio, primary and secondary, both sexes (%)")
 
```


```{r Morocco data}

Morocco <- userBasedData_raw %>%
  select(Country.Name,Country.Code,Series,X2018..YR2018.)%>%
 filter(Series %in% c("PISA: Mean performance on the science scale", "PISA: Mean performance on the reading scale","PISA: Mean performance on the mathematics scale","Youth literacy rate, population 15-24 years, both sexes (%)","GDP at market prices (current US$)	","GDP at market prices (current US$)","Government expenditure on education as % of GDP (%)"))

list_NAs<-which(is.na(Morocco))
Morocco1<-Morocco%>%
  pivot_wider(names_from=Series,values_from=X2018..YR2018.)

Morocco1_PISA<-Morocco1%>%
  filter(!is.na(`PISA: Mean performance on the science scale`)&!is.na(`PISA: Mean performance on the reading scale`)&!is.na(`PISA: Mean performance on the mathematics scale`))%>%
  select(Country.Name,Country.Code,`PISA: Mean performance on the science scale`,`PISA: Mean performance on the reading scale`,`PISA: Mean performance on the mathematics scale`)%>%
  mutate(AVG_PISA=(`PISA: Mean performance on the science scale`+`PISA: Mean performance on the reading scale`+`PISA: Mean performance on the mathematics scale`)/3)

write.xlsx(Morocco1_PISA, file = "Morocco_PISA.xlsx",
      sheetName = "MoroccoPisa", append = FALSE)

Morocco1_Lit<-Morocco1%>%filter(!is.na(`Youth literacy rate, population 15-24 years, both sexes (%)`))%>%
  select(Country.Name,Country.Code,`Youth literacy rate, population 15-24 years, both sexes (%)`)

write.xlsx(Morocco1_Lit, file = "Morocco_lit.xlsx",
      sheetName = "MoroccoLit", append = FALSE)

```

```{r Morocco data 1}
Moroccos <- userBasedData_raw %>%
  select(Country.Name,Country.Code,Series,X2017..YR2017.)%>%
 filter(Series %in% c("Gross enrolment ratio, secondary, both sexes (%)"))

Moroccos<-Moroccos%>%
  filter(!is.na(X2017..YR2017.))
#Moroccos$X2017..YR2017.[which(Moroccos$X2017..YR2017.>100)]=100 
Moroccos<-Moroccos%>%
  pivot_wider(names_from=Series,values_from=X2017..YR2017.)
 
write.xlsx(Moroccos, file = "Morocco_gross_enrol1.xlsx",
      sheetName = "Morocco_gross_enrol", append = FALSE)

```

```{r Morocco secondary education}
primary_secondary_raw<-read.csv(file="primary_secondary.csv",header=TRUE,na.strings=c("..","NA"))

primary_secondary <- primary_secondary_raw %>%
  select(Country.Name,Country.Code,Series,`X2017..YR2017.`) %>%
   filter(!is.na(X2017..YR2017.)) %>%
 filter(Series %in% c("Net enrolment rate, secondary, both sexes (%)"))%>%
  pivot_wider(names_from=Series,values_from=X2017..YR2017.)

 
write.xlsx(primary_secondary, file = "Morocco_net_secondary.xlsx",
      sheetName = "Morocco_net_secondary", append = FALSE)

```
